### ISSUE TITLE
Breaks cards editor with anki 2.1.29

### ISSUE THREAD

**Issue by grossherr** [Arthur-Milchior/anki-any-cloze-in-preview#2]
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-07-28 14:04:39

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 490, in handler
  File "aqt/editor.py", line 479, in <lambda>
  File "aqt/editor.py", line 357, in _onCardLayout
TypeError: __init__() got an unexpected keyword argument 'fill_empty'

**Comment by Arthur-Milchior** [comment]
Thanks for the report. 
Normally, it will be "fixed" next time you sync add-ons, because it will be deactivated. This feature is now directly incorpated in anki, so there is no need for the add-on anymore.
